### ISSUE TITLE
No longer seeing update button (portable version)

### ISSUE THREAD

**Issue by saas786** [Dziemborowicz/Hourglass#120]
Latest release is no longer showing update button when I change either "Title" or "Time"?

**Comment by Dziemborowicz** [comment]
The "Update" button shows when there is a new version of Hourglass available for download. If you are running the latest version, it should not show up.

**Comment by saas786** [comment]
Oh I see, I thought it was for updating timer, than how do I save timer for later use? (As automatically sometimes it saves it and sometimes not).

**Comment by Dziemborowicz** [comment]
Currently, only automatic saving happens. There is a feature request here for the ability to save custom presets: #88.
