### ISSUE TITLE
Add own sound

### ISSUE THREAD

**Issue by EMLVIRUS** [dziemborowicz/hourglass#128]
I can't find this anywhere but it is said to be supported on https://chris.dziemborowicz.com/apps/hourglass/

**Comment by dziemborowicz** [comment]
There is an FAQ towards the bottom of the page at https://chris.dziemborowicz.com/apps/hourglass/.

Save the sound file to the folder where you installed Hourglass – typically, C:\Program Files (x86)\Hourglass.

Your sound file should then appear when you right-click on any empty space in the Hourglass window and select the Sound submenu.

The supported formats are .aac, .m4a, .mid, .midi, .mp3, .wav, and .wma. If your sound file is not in one of the supported formats, you will need to convert it first.

**Comment by EMLVIRUS** [comment]
That can be weird. I can find nothing but Hourglass.exe in the installing folder,
It won't help even if I create it myself nor use repairing in the install pack.
PS I'm using Windows 10.14393.351

**Comment by dziemborowicz** [comment]
That's all that should be there. If you want to add your own custom sounds, you can just copy them into that folder so that they sit next to Hourglass.exe. The sounds will then appear in the "Sounds" right-click menu. (The built-in sounds are embedded in Hourglass.exe itself.)
