### ISSUE TITLE
Add option to "Count Up after count Down"

### ISSUE THREAD

**Issue by jtbrown3** [dziemborowicz/hourglass#134]
This is a very handy feature to have when giving presentations - If one goes over the allotted countdown time, then the app tells you how much time has passed since "time up"!   Many other timer apps support this feature.  Please include!

**Comment by dziemborowicz** [comment]
When the timer expires, it should already show "Timer expired" and then underneath "X seconds ago". Were you looking for something different?

**Comment by jtbrown3** [comment]
Gosh Chris, When I tested this with the dark theme I guess I just missed the smaller text underneath altogether!  Thanks for pointing out the obvious!  Perhaps I'd just recommend a brighter text/font color for the dark themes.  Also would be nice to have the option to see both the elapsed + remaining time.  Nice Job on this great timer!  -JT
