### ISSUE TITLE
No custom sound when time is up after Windows Update

### ISSUE THREAD

**Issue by Hnous927** [dziemborowicz/hourglass#143]
Hello! I've been using Hourglass for a long time. I just updated Windows 10 home 64bit yesterday and found there's a problem with Hourglass: 
When the time is up, no custom sound is emitted. The Loud, Normal and Quiet beep sound works though. Just the custom sound that doesn't work.
I tried the latest installed 1.8 version, latest portable 1.8 version, portable 1.7 version. All don't work. I believe this is caused by the Windows Update. How do I resolve such issue? I love this program and don't want to switch. Thank you.

**Comment by dziemborowicz** [comment]
Can you attach a copy of the sound file that doesn't work (or email it to me)?

Converting it to *.wav may fix the problem.

**Comment by Hnous927** [comment]
Thank you for getting back to me. I really appreciate your help. I tried
converting it to .wav but it doesn't work either.

Here are the mp3 files that I tested with. Actually all custom sound files
would not work.

Thank you and I look forward to hearing from you soon!

**Comment by dziemborowicz** [comment]
It looks like the files didn't attach to the GitHub issue... Can you attach them here: https://github.com/dziemborowicz/hourglass/issues/143?

**Comment by Hnous927** [comment]
I'm sorry for the mistake. Here are the links to the sample mp3 files:
https://soundcloud.com/user-9106363/victory-1
https://soundcloud.com/user-9106363/intro-1
https://soundcloud.com/user-9106363/start-1

Thank you again!

**Comment by Hnous927** [comment]
Hello! I rolled back to previous Windows 10 update and this issue is SOLVED! Hourglass works with custom sound again. Therefore, I am sure this is Windows 10 update related issue. It is fine with Windows 10 64 bit Home version 1511, OS Build 10586.916. I am not certain whether it would work with update further than this built.
I hope you find the issue behind this. Thank you for getting back to me. I hope you have a good day:)

**Comment by dziemborowicz** [comment]
The latest build of Windows 10 bricked my computer entirely, to the point where even restore did not work. I had to do a clean install...

That said, I am running the latest version currently, and Hourglass is able to play the sounds correctly. I'm not sure why it might not be working for you... especially if it is working with the built-in sounds.

Does Media Player in Windows work? Other sounds? Other apps? What if you reinstall audio drivers?

**Comment by Hnous927** [comment]
I'm sorry to hear that. I have no idea either. Media Player works in Windows. Everything is fine except the custom sound. Though it works fine for now because of restoring to previous build. I hope future Windows update would somehow fix this issue for me.
Thank you again for helping me:)

**Comment by dziemborowicz** [comment]
Alright. I'm going to close this now, as there isn't much I can do about it on my end. Perhaps Microsoft should hear about it. ;)

**Comment by Hnous927** [comment]
uyuy
