### ISSUE TITLE
Commandline option

### ISSUE THREAD

**Issue by MvErven** [dziemborowicz/hourglass#147]
I created a cmd file to start hourglass. In this file I set my title to 'verify log'
This is a job I need to do 5 days a week at given time. 

- Can I loop this one instance for mon, thu, wed, thu, fri (In other words, can I have 1 line command for every workday, or do I need 5 lines for each day? 

(I'm missing some advanced command line examples)

**Comment by dziemborowicz** [comment]
You will need to use a separate command line for every day. The command line interface doesn't support starting multiple timers with one command line, and it probably won't in the future either (it's too complicated for most uses).
