### ISSUE TITLE
Commandline -File option

### ISSUE THREAD

**Issue by MvErven** [dziemborowicz/hourglass#149]
I have a question for the command line part.

Throughout the day I've got to verify 40 import files at different time moments.

So I created a CMD file with lots of hourglass instances.
Would it be -nice to have-  a "schedule-file" where you could store these 'lines'?
Having one instance running, and pops-ups when the timer expires at each schedule.

hourglass.exe -file "C:\program files(x86)\Hourglass\myschedules.txt"
Options would be stored into this txt/ini/hourglass file.

**Comment by dziemborowicz** [comment]
I think this is probably a use that is too specific to be included as a feature in a simple timer like Hourglass.

What you could do, though, is create a *.bat file that starts multiple timers in sequence and use that. You can use the START command with the /WAIT parameter to start each timer in sequence, passing --close-when-expired on to Hourglass to ensure that Hourglass actually exits after the timer expires.

For example, something like the below should run a 5-minute timer and then a 10-minute timer and then a 15-minute timer:

```bat
START /WAIT "" "C:\Program Files (x86)\Hourglass\Hourglass.exe" --close-when-expired on 5m
START /WAIT "" "C:\Program Files (x86)\Hourglass\Hourglass.exe" --close-when-expired on 10m
START /WAIT "" "C:\Program Files (x86)\Hourglass\Hourglass.exe" --close-when-expired on 15m
```

**Comment by MvErven** [comment]
Well, thanks for your explaination. Will have a look at this.
