### ISSUE TITLE
Plz support 24-hour system 

### ISSUE THREAD

**Issue by LakeishaKowalczyk** [dziemborowicz/hourglass#168]
「14:23」 Could be used as a substitute for 「2:23 pm」

**Comment by foxx1337** [comment]
It actually works like this, it's just not documented:

```until 14:23```

will correctly handle it.

**Comment by edgimar** [comment]
I know this is closed, but I'd like to be able to either type just '14' (for a number of minutes -- it's rare that people need to specify seconds) or '14.23' (2:23 PM), without needing to type 'until'.  Maybe if you're concerned about backward compatibility (?), you could just add an additional commandline flag that enables this kind of interpretation of numbers in the NN.NN form.
