### ISSUE TITLE
Option to make Progress Bar SHRINK instead of GROW

### ISSUE THREAD

**Issue by todsandberg** [dziemborowicz/hourglass#183]
There is much to love about this app...

One thing that would make it even better for me would be to have an option so that users could have the progressbar start out FILLED and then it DISAPPEARS over time, (rather than growing).

**This feature would highlight the [REMAINING TIME] in BLUE, rather than the [ELAPSED TIME] in blue.**

So, the way it would work is that when you set a 30 minute timer, it would be all blue. When you have 10 minutes left it would be 33% blue. When the last bit of blue disappears, the alarm goes off.

Could you add an option for "Bar Vanishes" or "Bar Grows"?
Thanks for your consideration!

**Comment by dziemborowicz** [comment]
There is actually a pull request for that feature here: https://github.com/dziemborowicz/hourglass/pull/182.

I expect to merge that as soon as I have a minute to test it. I've been swamped at work recently...

**Comment by todsandberg** [comment]
Thanks for the update. It's good to know it's already in the works!
I understand... this is not your main thing.

I saw your comments in #182...
There are two other places where progress bars appear in the app: in the
taskbar and in the "Saved timers" menu. I don't know whether it might make
sense to reverse both of those too.

I think that does make sense... I didn't even know about the "Saved
Timers"... I'll have to learn how that works.

I definitely prefer to have the TASKBAR shrink as well. Since that is a
good indicator of time left (in the day/ for a project)

What software is this written in? Would I be able to open it in Visual
Studio? or would you recommend another system? I'd like to play with the
code. Sorry, to ask this, I don't know where to find out the language on
GitHub yet.

Thanks again!
Tod

**Comment by dziemborowicz** [comment]
You can click the green horizontal bar [here](https://github.com/dziemborowicz/hourglass), which will reveal that this project is 100% C#. Visual Studio will work. :)

I agree that it would make sense to reverse the other places also. It shouldn't take long, though I probably won't be able to do it any time soon. I'm not sure if @fmuecke is working on it.

**Comment by todsandberg** [comment]
Thank you for the tip.

I tried to compile but I don't have the newest version of Visual Studio (I
think that's what causing errors when compiling). I can't upgrade at work
(where I have VS) because the admin is locked down.

Is there any way you could email me the complied exe (no install, just the
exe) if you have it?
Sorry to trouble you.

If you can't maybe I could install and compile on a home PC.

Thanks!

**Comment by todsandberg** [comment]
Quick Update. I was able to get VS installed and compiled it. Excited to
use it with "Reverse progressbar"!
Thanks again!

**Comment by dziemborowicz** [comment]
Sorry for the delay responding to this, but it looks like you got it working! :)
