### ISSUE TITLE
Minimize stopped working in current build

### ISSUE THREAD

**Issue by todsandberg** [dziemborowicz/hourglass#187]
I just built the current version (as of 5/2/2019) and when I click minimize, the window does goes away but then immediately pops back up. 

Basically Minimize button doesn't work. It was working on the version just before Reverse Progress Bar feature was added. I hope this helps.

**Comment by dziemborowicz** [comment]
Can you confirm what specific commit you are building that is failing, and what is the last commit that you can build where this worked as before?

**Comment by todsandberg** [comment]
Just be be clear... The build wasn't failing to build. it's just that the minimize button doesn't work... Other than that everything works great. 

I just downloaded your most recent portable version 1.10 and it worked fine there. so, it seems that something may have changed between that version and when reverse progressbar option was added (aka the development version).

I tried stepping through the code, but don't know how to fix the issue.

I found this link that seems to show the diff. but you probably know a better way...
https://github.com/dziemborowicz/hourglass/compare/v1.10.0...develop

I wish I had more info for you.

I was able to get the progressbar to reverse (shrink instead of growing). but, I don't know how to "merge" that with github into your code. I'd want you to review it first before merging anything.

**Comment by dziemborowicz** [comment]
This should now be fixed. It was introduced by c874899b90751a9459a5661275894073255aacd7.

**Comment by dziemborowicz** [comment]
There is a "Reverse progress bar" option under "Advanced options" in the latest commit.

**Comment by todsandberg** [comment]
Thank you!! I'm excited that minimize and the "reverse progress bar" feature work perfectly at the same time!
In my note above I was referring to the taskbar (the green shrinking when reverse was enabled... instead of growing) I see that you improved that as well!

Thank you much! Just downloaded and compiled it.

**Comment by todsandberg** [comment]
Thanks for being awesome!
You Rock!
