### ISSUE TITLE
buliding causes some arguments to Fail or not working like --title

### ISSUE THREAD

**Issue by MNAJIM75** [dziemborowicz/hourglass#189]
When i downloaded the repo, I tried to build the project in Released Portable | Mixed Platform, it gone pretty well, and it runs so very good, but it doesn't work with arguments, or it doesn't work with --title at least , i didn't try them all.

ex:
in powershell:
PS C:\Test\hourglass\Hourglass.Test\bin\Debug Portable> ./Hourglass --title Tea_To_Boil
or
PS C:\Test\hourglass\Hourglass.Test\bin\Debug Portable> ./Hourglass --title "Tea To Boil"

The Program start but the title is not set to Tea To Boil.
I guess that the other args work like ( 5 ,--full-screen, etc ).

**Comment by dziemborowicz** [comment]
Does it work at the last public release (87e6d2a44a690249f1eefdf1a11866690058be77)? If so, can you identify which commit since then broke it?

**Comment by MNAJIM75** [comment]
it's working great with the public release, even after changing some Values in Properties.Resource, it worked fine, that what i did the last time, but i don't think that that's what caused the issue.
