### ISSUE TITLE
Vertical height can be more lowered

### ISSUE THREAD

**Issue by ky-japan** [dziemborowicz/hourglass#194]
Hello. I am a Japanese "Orzeszek Timer" user and I tried "Hourglass" this time.
And I found that the only inconvenience point of "Hourglass" was that the vertical height cannot be shorter than a certain length.  I want to use "Hourglass" in a small area.
I would be happy if you could address this in the future.
Thank you.

**Comment by dziemborowicz** [comment]
Closing as duplicate of #90.
