### ISSUE TITLE
Any chance you could tag and build a new release?

### ISSUE THREAD

**Issue by Darthagnon** [dziemborowicz/hourglass#199]
Please could you tag and build a new release? From the commits/issues, it seems a feature or two has been added since the last release in 2018, and the last commit was in 2019. We're getting close to 2021.

I can try and build one, but it wouldn't be the same as having a new Official Release™...

**Comment by dziemborowicz** [comment]
I will try to find some time to figure this out. I need to renew the code signing certificate for the release, which is a pain. And would you believe me if I told you that I don't currently own a working computer that can run Windows? :|

**Comment by Darthagnon** [comment]
Indeed I do believe you; don't blame you with the shenanigans Microsoft's been pulling. Thank you so much for replying. Best wishes, and Merry Christmas!

**Comment by PtrJsn** [comment]
@dziemborowicz - Microsoft has free VM's running Windows 10 & dev tools (like Visual Studio 2019 & VS Code) available on their web site. That should get you a "working computer" running Windows quickly, if that's feasible for you. https://developer.microsoft.com/en-us/windows/downloads/virtual-machines/

**Comment by dziemborowicz** [comment]
Apologies to everyone waiting for this release for so long. I have got a working(-ish) Windows computer again, I've got my updated code signing certificate, and this should be ready for a new release this weekend. Just fixing and verifying some bugs introduced with the recent changes.

**Comment by dziemborowicz** [comment]
[v1.11.0](https://github.com/dziemborowicz/hourglass/releases/tag/v1.11.0) is now tagged and released.
