### ISSUE TITLE
Interprets "hh:mm today" as PM for some reason

### ISSUE THREAD

**Issue by tim-247** [dziemborowicz/hourglass#204]
If I set a timer at 03:00 (am) and put something like "today 06:50", it counts down to 18:50 (6:50 PM). Why does it assume PM in the absence of an AM/PM signifier? Shouldn't it assume a 24h time?

**Comment by dziemborowicz** [comment]
I forget the exact logic, which perhaps suggests it's not the most intuitive. It assumes am/pm based on what it thinks is more likely depending on the current time of day and the sorts of timers that most people (I assume) would start.

Really, this needs a proper 24h time support as you say.

**Comment by CalAlaera** [comment]
Came here to post this exact issue, I'd argue that the leading zero makes 06:50 more likely to be in 24h format rather than the less-used (in my locality, anyway) am/pm format, but it seems you already know that. Thanks. :)

**Comment by dziemborowicz** [comment]
I've added a new "Prefer 24-hour time when parsing" option under "Advanced options" that will hopefully resolve this: times are always interpreted as 24-hour time with this option (unless you explicitly specify "am" or "pm", of course). The release with this change should be coming soon.
