### ISSUE TITLE
Dot NET 5.0/6.0 Compiled?

### ISSUE THREAD

**Issue by hl2guide** [dziemborowicz/hourglass#211]
Please consider compiling with .NET 5.0.

It should have worthwhile performance improvements.

**Comment by PtrJsn** [comment]
FYI, [.NET 6.0 is in preview & will be released on November 9](https://devblogs.microsoft.com/dotnet/announcing-net-6-preview-4/), & is an LTS release supported for 3 years, compared with .NET 5.0's 1 1/2 years. Given the level of development activity on Hourglass, LTS might be more suitable. That said, I'm sure the effort of upgrading to .NET 6.0 from 5.0 is less than upgrading from its current .NET Framework 4.5, though I wouldn't expect either to be massive.

I'd be interested in contributing if you're looking for help!

**Comment by dziemborowicz** [comment]
Given how close .NET 6.0 is to release, it probably makes sense to wait and do a one-time migration.

I haven't had time to see how much work it would be to migrate to .NET 5.0 or .NET 6.0. I agree it's probably not a lot of work, though some window magic (full screen, no title bar, dark mode, etc.) may require some attention. And the installer will need to be updated to not install .NET Framework 4.5 any more. This shouldn't be necessary with the single file application support that is now available.

**Comment by hl2guide** [comment]
Hoping that a migration to .NET 6.0 is in the works 😎

**Comment by hl2guide** [comment]
Hoping that a migration to .NET 7.0 is in the works 🤞 @dziemborowicz 

The claimed performance improvements could be nice to have.

**Comment by i2van** [comment]
Doable, but makes no sense.
