### ISSUE TITLE
1.12 Installer stuck on "Initializing..." 

### ISSUE THREAD

**Issue by JohannesMP** [dziemborowicz/hourglass#212]
I had a previous installer version of hourglass installed (I'm assuming 1.11) and saw the 'upgrade' button in the timer UI, so have downloaded the latest installer by following that link, "Hourglass 1.12 Installer" via https://chris.dziemborowicz.com/apps/hourglass/#downloads

I've shut down my hourglass instance and have verified the process is not running.

When I launch the new installer it just freezes on "Processing:    Initializing..."

![image](https://user-images.githubusercontent.com/662874/135142988-d29208ea-c10e-4dcb-83fa-c7a125220ce0.png)

I see no further dialogue boxes or info.

**Comment by JohannesMP** [comment]
Further info: When in this state, even clicking 'Cancel', clicking the 'close window' button in the top right, or right clicking the setup icon in the taskbar and choosing 'close window' makes no difference. I have to use the task manager to force close the setup process.

**Comment by dziemborowicz** [comment]
Did retrying fix the issue? What about restarting the computer?

I've noticed the installer can sometimes take a while (longer than you would think)...

**Comment by JohannesMP** [comment]
This may be due to the state of my machine. It’s having other issues with restarting and Windows updates right now, so I’m closing this for the time being. 

I will re-open the issue of it persists once my computer is in completely working order again.
