### ISSUE TITLE
v1.12+ doesn't display progress on taskbar icon

### ISSUE THREAD

**Issue by redactedscribe** [dziemborowicz/hourglass#215]
If I'm not mistaken, Hourglass used to display the remaining time as a green progress "bar" across the width of the hourglass icon in the taskbar. Since at least v1.12, Hourglass doesn't do this any more.

Thanks.

**Comment by dziemborowicz** [comment]
This still works for me in Hourglass 1.13. Can you double check that the "Show progress in taskbar" option is selected?

![Screenshot](https://user-images.githubusercontent.com/1935368/135841806-a6e66bfe-6e9c-4731-ac84-b085b32a85c2.png)

It's possible that the setting was lost during the update.

**Comment by redactedscribe** [comment]
Ah, you're right, it was unchecked. I don't recall unchecking it as I haven't changed Hourglass' settings since configuring it on installation a long time ago. I had forgotten there was even an option for it. I must've miss-clicked recently as the other settings still seem customised.

Thanks again.
