### ISSUE TITLE
(request) show title in the taskbar, instead of "Hourglass"

### ISSUE THREAD

**Issue by Micke3rd** [dziemborowicz/hourglass#222]
Hi Chris,
in my use case I have multiple minimized or not on top hourglasses.
problem: the taskbar shows for all the title "Hourglass" , and therefore its unclear to what the countdown belongs.

title + "HourGlass" would also be fine

Perhaps use the switch `<WindowTitleMode>ApplicationName</WindowTitleMode>`  @HourglassPortable.config for this  ?

thnx in advance

**Comment by dziemborowicz** [comment]
I'm out of town at the moment and don't have a convenient way to check to make sure, but I thought there was an option under "Advanced options" > "Window title" > "Timer title" or something similar that does this already.
