### ISSUE TITLE
Feature Request: Ticking sound per second

### ISSUE THREAD

**Issue by CommaWriter** [Dziemborowicz/Hourglass#227]
I'd like to thank you for making such a simple yet useful program. I've been using it to give myself a sense of urgency in my tasks: framing tasks as a countdown instead of a regular clock counting things up can be a game-changer.

Thus, I'd like to request a ticking sound per second, like a less intense version of the clock from the TV show "24". There can be times when both having music and having nothing but silence can be distracting, so something that can keep an "audio routine" or a drumbeat for the brain while working can surely be a feature to look into.

Looking forward to your response!

**Comment by dziemborowicz** [comment]
Thank you for the feedback and suggestion. I'm going to close this issue because this feature is already requested in #72. There does seem to be some demand for this kind of feature (though in the meantime there are several other apps that will play various types of white noise while you work).
