### ISSUE TITLE
Mac Version? Would love to help

### ISSUE THREAD

**Issue by mattpetters** [Dziemborowicz/Hourglass#229]
This app is sick, best countdown timer I've ever used. I'd love to port it to Mac. Have you considered this? Wondering the lift it would take to do with .NET core, lest a full re-write be necessary @dziemborowicz

**Comment by dziemborowicz** [comment]
It's been requested a few times via email and on GitHub in #174 (closing this issue as a dupe).

I haven't looked into how much work it would be to just do a .NET Core version. Everything is built on an older version of WPF, so it won't just compile with .NET Core... but probably not much work to get it there.
