### ISSUE TITLE
Program Doesnt start anymore

### ISSUE THREAD

**Issue by m4nttty** [Dziemborowicz/Hourglass#231]
Since some weeks ago whenever I try to start it the only thing it gives is a crash report saying 
`An unexpected error has occurred` whit the only option being to close it and I just cannot use it anymore due to it not starting
I put the reports the program gives in the temp folder on the embeeded 

[Hourglass-Crash.20220928-130909-6481919.txt](https://github.com/dziemborowicz/hourglass/files/9667069/Hourglass-Crash.20220928-130909-6481919.txt)
[Hourglass-Crash.20220928-130949-8489509.txt](https://github.com/dziemborowicz/hourglass/files/9667070/Hourglass-Crash.20220928-130949-8489509.txt)
[Hourglass_20220928120910.log](https://github.com/dziemborowicz/hourglass/files/9667071/Hourglass_20220928120910.log)

**Comment by dziemborowicz** [comment]
This can sometimes happen when the Hourglass settings file becomes corrupted on the disk, and so Hourglass crashes when it tries to load settings after starting up.

The solution is to delete the following folder:

```
C:\Users\<your_username>\AppData\Local\Chris_Dziemborowicz\Hourglass.exe_Url_<some_random_characters>
```

For example, it might look like --

```
C:\Users\M4nty\AppData\Local\Chris_Dziemborowicz\Hourglass.exe_Url_la3v0chg0cfk1mkapgxkzi2xaouqgqcm
```

This means that, unfortunately, any settings you may have customized will be reset, but hopefully the app will work again.

(If that doesn't work, try the portable version to see if that works. You can download it [here](https://chris.dziemborowicz.com/apps/hourglass/#downloads).)

**Comment by m4nttty** [comment]
Yeah, that fixed it, thanks!
