### ISSUE TITLE
Feature Request: pre-configured desktop shortcuts

### ISSUE THREAD

**Issue by nr1995** [Dziemborowicz/Hourglass#239]
Hi, noob here.
Is there a way to create pre-configured desktop shortcuts for Hourglass,
such that I can just double-click on it,
and it'll open up an Hourglass window with a pre-configured countdown and label?
If not could that feature be added in somehow?
Thanks!

**Comment by dziemborowicz** [comment]
There is unfortunately no nice UI built-in to do this, but you can create one manually by following the instructions found [here](https://chris.dziemborowicz.com/apps/hourglass/) under --

- "How do I create a shortcut that automatically starts a timer with Hourglass?"
- "What command line arguments does Hourglass accept?"
