### ISSUE TITLE
Prevent (or option to prevent) stealing focus when timer is up

### ISSUE THREAD

**Issue by mishaxz** [Dziemborowicz/Hourglass#255]
It is quite distracting when the timer window pops up when it has expired, and steals focus. 

Often I'm in the middle of typing, and focus shifts away from my IDE and i type some characters into the timer window.

Can you either not make it steal focus (i.e. not become the active window) .. or .. have an option to disable it from stealing focus/becoming active window?

I use the timer to tell me to take a break, so I the timer will complete many times a day

**Comment by asjones987** [comment]
You may want to look at the the fork of this project https://github.com/i2van/hourglass

The project has not had much in the way in the way of updates in a while.

**Comment by i2van** [comment]
Duplicate of #121 

I plan to fix it in the [fork](https://github.com/i2van/hourglass)

**Comment by mishaxz** [comment]
great, thanks

**Comment by i2van** [comment]
Fixed [here](https://github.com/i2van/hourglass/releases/latest).
