### ISSUE TITLE
Add About dialog or similar to show current version information

### ISSUE THREAD

**Issue by dziemborowicz** [dziemborowicz/hourglass#78]

**Comment by dziemborowicz** [comment]
A link back to the website would be useful too. Unfortunately, Google searches for "Hourglass" do not typically return this app...

**Comment by EMLVIRUS** [comment]
@dziemborowicz if you actually hope higher Google rankings, maybe a quick SEO will be necessary

**Comment by asjones987** [comment]
See there a few source code updates in 2019. Love to see an About Screen with info and link to web page and Github page.  Maybe as part of the right click with the last option being "About".

Love to see a new version in with a few things added/corrected in the near future. Keep up the good work.

**Comment by dziemborowicz** [comment]
I hope to get some of those changes published, but my code signing certificate has expired and I'm dragging my feet on organizing a replacement. It's quite a pain...

**Comment by Riajyuu** [comment]
@dziemborowicz 
Why not post it to Microsoft Store, it doesn't require any code signing but a small one-time fee for open source projects.

**Comment by dziemborowicz** [comment]
That's definitely on the to-do list as well (#140).

**Comment by asjones987** [comment]
Love to see something like this
![image](https://user-images.githubusercontent.com/30843311/135287038-2ad0e978-4e5a-4b64-929f-c023333a2d20.png)

**Comment by dziemborowicz** [comment]
The next release of Hourglass will have an about dialog reachable from the context menu:

![AboutDialog](https://user-images.githubusercontent.com/1935368/135818402-ce9be51c-f159-4a79-a870-8f3c56ebb00b.png)

**Comment by asjones987** [comment]
Very nice. This helps to ensure you get the credit you deserve.
