### ISSUE TITLE
Installer complains about insufficient memory

### ISSUE THREAD

**Issue by nkmathew** [Dziemborowicz/Hourglass#81]
![shot](http://i.imgur.com/OFw4jbs.png)

**Comment by Dziemborowicz** [comment]
A few questions to help identify the problem:

Could you post your system information (CPU, RAM, OS, etc.) and a screenshot of task manager showing memory usage?

Does the problem persist after a restart?

Does the problem affect only Hourglass?

Did you pass any command-line arguments to Hourglass?

**Comment by nkmathew** [comment]
![](http://i.imgur.com/2t72UvW.png)
Just noticed it works ok when launched from the file manager, fails when ran from the download manager. Not sure how it runs programs

![](http://i.imgur.com/6KqxiFq.gif)

**Comment by Dziemborowicz** [comment]
I tried to repro this in Internet Download Manager 6.25 on Windows 10 x64, and it didn't repro. I'm not sure what is going on here.

**Comment by Dziemborowicz** [comment]
Closing this issue, since it seems to be an issue with Internet Download Manager rather than Hourglass. And, in any event, there is an easy workaround -- run from File Explorer.
