### ISSUE TITLE
Feature requests: actions with clicking hourglass icon on notification area

### ISSUE THREAD

**Issue by mindstormer12** [Dziemborowicz/Hourglass#85]
Some feature requests not already listed under "issues" at the time of this post:

- When "Show in notification area" is enabled, the following options are available:

   1) single-click to toggle timer on/off
   2) double-click to *toggle* window popup/minimize
   3) triple-click to restart timer with the time previously specified in the window
   4) automatically minimize window back to tray after a time has been entered

- Visual representation of progress in tray icon--for example, when half the specified time is elapsed, half of the sand is on top of the hourglass while half of the sand is down on the bottom, updated in real time.

- Buttons created on the window for preset timers created by the user (one-click-start timer)  for simplicity and convenience (this may go against the simple look of the timer but it can be implemented to be aesthetically pleasing).

On an unrelated note, it is very difficult to find this application when searching through Google using the keywords "hourglass" and "hourglass timer" (and "orzeszek timer").

**Comment by Dziemborowicz** [comment]
Could you break the bullet points out into separate issues for tracking?

I'm aware of the Google problem. I'm going to have to do something about that, just not time to address it at the moment. :)

**Comment by mindstormer12** [comment]
Done.

**Comment by Dziemborowicz** [comment]
Thanks. :)

These requests are now tracked by #86, #87, and #88.
