### ISSUE TITLE
Option to not keep screens active

### ISSUE THREAD

**Issue by variab1e** [Dziemborowicz/Hourglass#94]
Great  program, EXACTLY what I was looking for! One thing I found last night though - Currently (at least on my system) the monitors stay active, rather than ever shutting down when running hourglass, I could that as being a useful behavior

Thanks!, but also I would want the ability to turn that off if possible?

**Comment by Dziemborowicz** [comment]
This behavior was by design, though it is a good suggestion to have this be an option.
